# Generated by Django 3.0.7 on 2022-01-30 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pegawai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('idDevice', models.AutoField(primary_key=True, serialize=False)),
                ('jenis', models.CharField(max_length=50)),
                ('keterangan', models.TextField()),
                ('noBMN', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kasus',
            fields=[
                ('idKasus', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('pelapor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pegawai.Pegawai')),
            ],
        ),
        migrations.CreateModel(
            name='TindakLanjut',
            fields=[
                ('idTindakLanjut', models.AutoField(primary_key=True, serialize=False)),
                ('progres', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('idKasus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kasus.Kasus')),
                ('idPenindakLanjut', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pegawai.Pegawai')),
            ],
        ),
    ]
