# Generated by Django 3.0.7 on 2022-01-30 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kasus', '0002_kasus_buktifoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='kasus',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kasus.Device'),
        ),
    ]
