# Generated by Django 3.0.7 on 2022-01-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasus', '0004_auto_20220131_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='kasus',
            name='deskripsi',
            field=models.TextField(null=True),
        ),
    ]
