# Generated by Django 3.0.7 on 2022-01-31 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0003_auto_20220131_1615'),
        ('kasus', '0003_kasus_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='kasus',
            name='penindaklanjut',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pegawai.OperatorConsole'),
        ),
        migrations.AddField(
            model_name='kasus',
            name='progres',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='kasus',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='TindakLanjut',
        ),
    ]
