# Generated by Django 3.0.7 on 2022-01-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasus', '0005_kasus_deskripsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='kasus',
            name='tanggal_update',
            field=models.DateField(null=True),
        ),
    ]
